vich_uploader:
    db_driver: orm

    mappings:
        annonce_photo:
            uri_prefix: '%annonce_photo%'
            upload_destination: '%kernel.project_dir%/public%annonce_photo%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            # inject_on_load: false
            # delete_on_update: true
            # delete_on_remove: true